### ISSUE TITLE
plugin is not available

### ISSUE THREAD

**Issue by pgollor** [gitbucket/gitbucket-pages-plugin#15]
Hi Guys,

i want to use this plugin and followed the installation instructions but it doesn't work.
All other plugin files in the plugin directory are working (like gist plugin, network plugin and so on).
I tried to rename the file into `gitbucket-pages-plugin_2.12-1.1.jar` but after a restart the plugin is not present under `System administration->Plugins` and `<your repo url>/pages` isn't working too.

Could anyone help me?
I use the gitbucket verison `4.11`.

thanks al lot

**Comment by aadrian** [comment]
> Could anyone help me?

Can you give us more details? E.g. Log files or more details about how and on what are you running it?

**Comment by pgollor** [comment]
- System: debian stable
- java: oracle 1.8.0_73
Does gitbucket generate logs? I could try to start it manually. Currently gitbucket runs with the debain `start-stop-deamon`.

**Comment by pgollor** [comment]
```
[main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: /srv/gitbucket/home/plugins/gitbucket-pages-plugin_2.12-1.1.jar
java.lang.IllegalStateException: Plugin version is 1.1, but database version is 3.9
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$1(PluginRegistory.scala:188)
        at gitbucket.core.plugin.PluginRegistry$.$anonfun$initialize$1$adapted(PluginRegistory.scala:175)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:193)
        at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:175)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1(InitializeListener.scala:111)
        at gitbucket.core.servlet.InitializeListener.$anonfun$contextInitialized$1$adapted(InitializeListener.scala:52)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$2(BlockingProfile.scala:190)
        at slick.JdbcProfileBlockingSession$BlockingSession.withTransaction(TransactionalJdbcBackend.scala:26)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.$anonfun$withTransaction$1(BlockingProfile.scala:190)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withSession(BlockingProfile.scala:183)
        at com.github.takezoe.slick.blocking.BlockingJdbcProfile$BlockingAPI$BlockingDatabase.withTransaction(BlockingProfile.scala:190)
        at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:52)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:837)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:810)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.server.Server.start(Server.java:411)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:378)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:91)
```

**Comment by aadrian** [comment]
> java: oracle 1.8.0_73

Please use a more recent JDK .

> ``` java.lang.IllegalStateException: Plugin version is 1.1, but database version is 3.9```

Was your the update to 4.11 successful ? Do you use H2 as a database ?

**Comment by pgollor** [comment]
> Please use a more recent JDK .
i will use 8u131

> Was your the update to 4.11 successful ? Do you use H2 as a database ?
Yes and yes

**Comment by aadrian** [comment]
>> Was your the update to 4.11 successful ? Do you use H2 as a database ?

> Yes and yes

From the error message it just looks like this https://github.com/gitbucket/h2-migration was not executed (if you migrated from early 3.x)

The database version should be 4.11 in your case, and all these scripts 
https://github.com/gitbucket/gitbucket/tree/master/src/main/resources/update
should have taken place.

To check if the they did, connect to the DB https://github.com/gitbucket/gitbucket/wiki/Connect-to-H2-database and check if those updates really took place.

If they did, than post here the content of the `versions` table, since it should do the trick just to increment the version there.

**Comment by pgollor** [comment]
> From the error message it just looks like this https://github.com/gitbucket/h2-migration was not executed (if you migrated from early 3.x)

I thouth i did it.
But if i deleted the pages line in the `VERSIONS` table it works.
Thanks a lot for your help.
